framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
#        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
#             sync: 'sync://'

            kafka_product_consumer:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Serializer\ProductMessageSerializer
                options:
                    topic:
                        name: "product"
                    queue:
                        name: "product"

            kafka_change_order_status_consumer:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Serializer\ChangeOrderStatusMessageSerializer
                options:
                    topic:
                        name: "order"
                    queue:
                        name: "order"

            kafka_generate_report:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    topic:
                        name: 'generate_report'
                    queue:
                        name: 'generate_report'

            kafka_report_generated_producer:
                serializer: App\Serializer\ReportGeneratedMessageSerializer
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    topic:
                        name: 'report_generated'
                    queue:
                        name: 'report_generated'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
